name: my-backend

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      PORT: "3000"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
